<?xml version="1.0" encoding="UTF-8"?><project name="DietApp Project" company="Diet Planner" webLink="http://www.example.com" view-date="2025-03-01" view-index="0" gantt-divider-location="300" resource-divider-location="300" version="3.2.3230" locale="en_US">
    <description>Diet Planner Application Development</description>
    <view zooming-state="default:6" id="gantt-chart">
        <field id="tpd3" name="Name" width="167" order="0"/>
        <field id="tpd4" name="Begin date" width="65" order="1"/>
        <field id="tpd5" name="End date" width="65" order="2"/>
        <option id="filter.completedTasks" value="false"/>
    </view>
    <view id="resource-table">
        <field id="0" name="Name" width="210" order="0"/>
        <field id="1" name="Default role" width="86" order="1"/>
    </view>
    <calendar>
        <day-types>
            <day-type id="0"/>
            <day-type id="1"/>
            <default-week id="1" name="default" sun="1" mon="0" tue="0" wed="0" thu="0" fri="0" sat="1"/>
            <only-show-weekends value="false"/>
            <overriden-day-types/>
            <days/>
        </day-types>
    </calendar>
    <tasks empty-milestones="true">
        <taskproperties>
            <taskproperty id="tpd0" name="type" type="default" valuetype="icon"/>
            <taskproperty id="tpd1" name="priority" type="default" valuetype="icon"/>
            <taskproperty id="tpd2" name="info" type="default" valuetype="icon"/>
            <taskproperty id="tpd3" name="name" type="default" valuetype="text"/>
            <taskproperty id="tpd4" name="begindate" type="default" valuetype="date"/>
            <taskproperty id="tpd5" name="enddate" type="default" valuetype="date"/>
            <taskproperty id="tpd6" name="duration" type="default" valuetype="int"/>
            <taskproperty id="tpd7" name="completion" type="default" valuetype="int"/>
            <taskproperty id="tpd8" name="coordinator" type="default" valuetype="text"/>
            <taskproperty id="tpd9" name="predecessorsr" type="default" valuetype="text"/>
        </taskproperties>
        
        <!-- Phase 1 -->
        <task id="1" name="Phase 1: Project Definition and Planning" color="#8cb6ce" meeting="false" start="2025-03-11" duration="5" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true">
            <task id="2" name="Project Description" color="#8cb6ce" meeting="false" start="2025-03-11" duration="2" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true"/>
            <task id="3" name="User saves food and nutrient data" color="#8cb6ce" meeting="false" start="2025-03-12" duration="1" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="2"/>
            <task id="4" name="Weekly/Monthly meal planning" color="#8cb6ce" meeting="false" start="2025-03-13" duration="1" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="3"/>
            <task id="5" name="Nutritional values analysis" color="#8cb6ce" meeting="false" start="2025-03-14" duration="2" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="4"/>
        </task>
        
        <!-- Phase 2 -->
        <task id="6" name="Phase 2: Basic Features Development" color="#8cb6ce" meeting="false" start="2025-03-17" duration="11" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="1">
            <task id="7" name="Basic Features" color="#8cb6ce" meeting="false" start="2025-03-17" duration="2" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true"/>
            <task id="8" name="User Login and Registration" color="#8cb6ce" meeting="false" start="2025-03-18" duration="2" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="7"/>
            <task id="9" name="Add/Edit/Delete Food" color="#8cb6ce" meeting="false" start="2025-03-19" duration="2" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="8"/>
            <task id="10" name="Nutritional Calculator" color="#8cb6ce" meeting="false" start="2025-03-20" duration="2" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="9"/>
            <task id="11" name="Meal Planner" color="#8cb6ce" meeting="false" start="2025-03-21" duration="2" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="10"/>
            <task id="12" name="Shopping List Creator" color="#8cb6ce" meeting="false" start="2025-03-24" duration="2" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="11"/>
            <task id="13" name="Data Storage" color="#8cb6ce" meeting="false" start="2025-03-25" duration="1" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="12"/>
            <task id="14" name="Personalized Diet Recommendations" color="#8cb6ce" meeting="false" start="2025-03-26" duration="2" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="13"/>
        </task>
        
        <!-- Phase 3 -->
        <task id="15" name="Phase 3: Technology Research and Design" color="#8cb6ce" meeting="false" start="2025-03-25" duration="7" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true">
            <task id="16" name="Technologies Research" color="#8cb6ce" meeting="false" start="2025-03-25" duration="3" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true"/>
            <task id="17" name="Inputs/Outputs" color="#8cb6ce" meeting="false" start="2025-03-27" duration="2" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="16"/>
            <task id="18" name="Data Storage Tech" color="#8cb6ce" meeting="false" start="2025-03-28" duration="2" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="17"/>
            <task id="19" name="Interface Research" color="#8cb6ce" meeting="false" start="2025-03-31" duration="2" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="18"/>
        </task>
        
        <!-- Phase 4 -->
        <task id="20" name="Phase 4: Class Design" color="#8cb6ce" meeting="false" start="2025-03-31" duration="5" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="15">
            <task id="21" name="Class Design" color="#8cb6ce" meeting="false" start="2025-03-31" duration="2" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true"/>
            <task id="22" name="User, Food, FoodNutrient" color="#8cb6ce" meeting="false" start="2025-04-01" duration="1" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="21"/>
            <task id="23" name="NutritionInfo, MealPlan" color="#8cb6ce" meeting="false" start="2025-04-02" duration="1" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="22"/>
            <task id="24" name="ShoppingList, AuthService" color="#8cb6ce" meeting="false" start="2025-04-03" duration="1" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="23"/>
        </task>
        
        <!-- Phase 5 -->
        <task id="25" name="Phase 5: Functional Requirements and Testing" color="#8cb6ce" meeting="false" start="2025-04-02" duration="7" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="20">
            <task id="26" name="Functional Requirements" color="#8cb6ce" meeting="false" start="2025-04-02" duration="1" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true"/>
            <task id="27" name="Test Plan" color="#8cb6ce" meeting="false" start="2025-04-03" duration="1" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="26"/>
            <task id="28" name="Unit Tests" color="#8cb6ce" meeting="false" start="2025-04-04" duration="1" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="27"/>
            <task id="29" name="Scenario Tests" color="#8cb6ce" meeting="false" start="2025-04-07" duration="1" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="28"/>
            <task id="30" name="Database Test" color="#8cb6ce" meeting="false" start="2025-04-08" duration="1" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="29"/>
            <task id="31" name="Invalid Input Test" color="#8cb6ce" meeting="false" start="2025-04-09" duration="1" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="30"/>
        </task>
        
        <!-- Phase 6 -->
        <task id="32" name="Phase 6: Documentation and Finalization" color="#8cb6ce" meeting="false" start="2025-04-04" duration="7" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="25">
            <task id="33" name="Documentation &amp; Delivery" color="#8cb6ce" meeting="false" start="2025-04-04" duration="3" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true"/>
            <task id="34" name="User Guide" color="#8cb6ce" meeting="false" start="2025-04-07" duration="1" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="33"/>
            <task id="35" name="Class Diagrams" color="#8cb6ce" meeting="false" start="2025-04-08" duration="1" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="34"/>
            <task id="36" name="Sample Outputs" color="#8cb6ce" meeting="false" start="2025-04-09" duration="1" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="35"/>
            <task id="37" name="Final Report" color="#8cb6ce" meeting="false" start="2025-04-10" duration="1" complete="0" thirdDate="2020-12-29" thirdDate-constraint="0" expand="true" depend="36"/>
        </task>
    </tasks>
    <resources>
        <resource id="0" name="Developer 1" function="Default:0" contacts="" phone=""/>
        <resource id="1" name="Developer 2" function="Default:0" contacts="" phone=""/>
    </resources>
    <allocations>
        <allocation task-id="2" resource-id="0" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="3" resource-id="1" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="4" resource-id="0" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="5" resource-id="1" function="Default:0" responsible="true" load="100.0"/>
        
        <allocation task-id="7" resource-id="0" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="8" resource-id="1" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="9" resource-id="0" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="10" resource-id="1" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="11" resource-id="0" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="12" resource-id="1" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="13" resource-id="0" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="14" resource-id="1" function="Default:0" responsible="true" load="100.0"/>
        
        <allocation task-id="16" resource-id="0" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="17" resource-id="1" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="18" resource-id="0" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="19" resource-id="1" function="Default:0" responsible="true" load="100.0"/>
        
        <allocation task-id="21" resource-id="0" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="22" resource-id="1" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="23" resource-id="0" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="24" resource-id="1" function="Default:0" responsible="true" load="100.0"/>
        
        <allocation task-id="26" resource-id="0" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="27" resource-id="1" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="28" resource-id="0" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="29" resource-id="1" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="30" resource-id="0" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="31" resource-id="1" function="Default:0" responsible="true" load="100.0"/>
        
        <allocation task-id="33" resource-id="0" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="34" resource-id="1" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="35" resource-id="0" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="36" resource-id="1" function="Default:0" responsible="true" load="100.0"/>
        <allocation task-id="37" resource-id="0" function="Default:0" responsible="true" load="100.0"/>
    </allocations>
    <vacations/>
    <previous/>
    <roles roleset-name="Default"/>
</project>