@startditaa
+------------------------------------------------------------------+
|                      Diet Planner Application                   |
+------------------------------------------------------------------+

+---------------+      +---------------+      +---------------+
| User Interface|----->| Business Logic|----->| Data Storage  |
| Layer         |      | Layer         |      | Layer         |
+---------------+      +---------------+      +---------------+
        |                      |                      |
        v                      v                      v
+---------------+      +---------------+      +---------------+
|cGRE           |      |cBLU           |      |cYEL           |
| GUI Components|      | Services      |      | SQLite DB     |
|               |      |               |      |               |
+---------------+      +---------------+      +---------------+

+--------------------------------------------------------------+
|                  Application Components                     |
|                                                              |
| +---------------+                                            |
| |cPNK           |                                            |
| | Authentication|                                            |
| | Panel         |                                            |
| +---------------+                                            |
|         |                                                    |
|         v                                                    |
| +---------------+                                            |
| |cPNK           |                                            |
| | Main Menu     |                                            |
| +---------------+                                            |
|    |         |           |                                  |
|    v         v           v                                  |
| +-------+ +-------+ +---------------+                      |
| |cBLU   | |cBLU   | |               |                      |
| | Meal  | |Calorie| | Diet          |                      |
| |Planning| |Tracking| |Recommendations|                      |
| |Module | |Module | |               |                      |
| +-------+ +-------+ +---------------+                      |
|    |                       |                               |
|    v                       |                               |
| +---------------+          |                               |
| | Shopping List |<---------+                               |
| | Module        |                                          |
| +---------------+                                          |
+--------------------------------------------------------------+
@endditaa